# Generated by Django 5.2.16 on 2026-07-16 07:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("waitlisted", "Waitlisted"),
                            ("cancelled", "Cancelled"),
                            ("walk_in", "Walk-in"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("needs_transport", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "registered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "checkin_method",
                    models.CharField(
                        blank=True,
                        choices=[("qr", "QR"), ("manual", "Manual")],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "event_registration",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("signup_opens", models.BooleanField(default=True)),
                ("signup_closes_at", models.DateTimeField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenancy.church"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "event",
            },
        ),
    ]
