# Generated by Django 5.2.16 on 2026-07-16 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_registrations",
                to="people.person",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["church", "starts_at"], name="event_church__f3c3f7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="event_ends_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capacity__isnull", True), ("capacity__gt", 0), _connector="OR"
                ),
                name="event_positive_capacity",
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["church", "event", "status"],
                name="event_regis_church__f42685_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventregistration",
            constraint=models.UniqueConstraint(
                fields=("event", "person"), name="uniq_event_registration_person"
            ),
        ),
    ]
