# Generated by Django 5.2.17 on 2026-08-12 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="cancellation_token_digest",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="PublicRegistrationRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_digest", models.CharField(max_length=64)),
                ("client_digest", models.CharField(max_length=64)),
                ("window_started_at", models.DateTimeField()),
                ("request_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "event_public_registration_rate_limit",
                "indexes": [
                    models.Index(
                        fields=["window_started_at"],
                        name="event_publi_window__5639d6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("token_digest", "client_digest", "window_started_at"),
                        name="uniq_public_registration_rate_window",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PublicRegistrationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenancy.church"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="public_registration_links_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_registration_link",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "event_public_registration_link",
                "indexes": [
                    models.Index(
                        fields=["church", "event", "revoked_at"],
                        name="event_publi_church__7b8e19_idx",
                    )
                ],
            },
        ),
    ]
