# Generated by Django 5.2.17 on 2026-08-12 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_eventregistration_cancellation_token_digest_and_more"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicRegistrationIdentityLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identity_digest", models.CharField(max_length=64)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenancy.church"
                    ),
                ),
            ],
            options={
                "db_table": "event_public_registration_identity_lock",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("church", "identity_digest"),
                        name="uniq_public_registration_identity_lock",
                    )
                ],
            },
        ),
    ]
