# Generated by Django 5.2.17 on 2026-09-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_remove_transport"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicregistrationlink",
            name="encrypted_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
