# Generated by Django 5.2.16 on 2026-07-16 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembership",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_memberships",
                to="people.person",
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["church", "kind", "is_active"], name="group_church__7085c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmembership",
            index=models.Index(
                fields=["church", "group", "left_at"],
                name="group_membe_church__5ae0cb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("left_at__isnull", True)),
                fields=("group", "person"),
                name="uniq_active_group_membership",
            ),
        ),
    ]
