# Generated by Django 5.2.16 on 2026-07-16 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenancy.church"
                    ),
                ),
            ],
            options={
                "db_table": "household",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=200)),
                (
                    "preferred_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unspecified", "Unspecified"),
                        ],
                        default="unspecified",
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("has_whatsapp", models.BooleanField(default=True)),
                ("photo_url", models.URLField(blank=True, max_length=500, null=True)),
                ("home_country", models.CharField(blank=True, max_length=2, null=True)),
                ("suburb", models.CharField(blank=True, max_length=100, null=True)),
                ("occupation", models.CharField(blank=True, max_length=200, null=True)),
                ("university", models.CharField(blank=True, max_length=200, null=True)),
                ("course", models.CharField(blank=True, max_length=200, null=True)),
                ("interests", models.JSONField(default=list)),
                (
                    "membership_status",
                    models.CharField(
                        choices=[
                            ("visitor", "Visitor"),
                            ("newcomer", "Newcomer"),
                            ("regular", "Regular"),
                            ("member", "Member"),
                            ("inactive", "Inactive"),
                        ],
                        default="visitor",
                        max_length=20,
                    ),
                ),
                (
                    "discipleship_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pre_evangelism", "Pre-evangelism"),
                            ("evangelism", "Evangelism"),
                            ("conversion", "Conversion"),
                            ("maturity", "Maturity"),
                            ("leadership", "Leadership"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "faith_background",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenancy.church"
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="people",
                        to="people.household",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitees",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "person",
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("friend", "Friend"),
                            ("family", "Family"),
                            ("spouse", "Spouse"),
                            ("guardian", "Guardian"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenancy.church"
                    ),
                ),
                (
                    "from_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_from",
                        to="people.person",
                    ),
                ),
                (
                    "to_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "relationship",
            },
        ),
        migrations.AddIndex(
            model_name="household",
            index=models.Index(
                fields=["church", "name"], name="household_church__b5a2cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["church", "full_name"], name="person_church__c0a5c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["church", "membership_status"], name="person_church__69feec_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("email__isnull", False), models.Q(("email", ""), _negated=True)
                ),
                fields=("church", "email"),
                name="uniq_person_email_per_church",
            ),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(
                fields=["church", "from_person"], name="relationshi_church__dc3940_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(
                fields=["church", "to_person"], name="relationshi_church__53a19b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="relationship",
            constraint=models.UniqueConstraint(
                fields=("from_person", "to_person", "kind"),
                name="uniq_relationship_pair_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="relationship",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_person_id__lt", models.F("to_person_id"))),
                name="relationship_canonical_order",
            ),
        ),
    ]
