# Generated by Django 5.2.16 on 2026-07-17 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("granted", "Granted"), ("declined", "Declined")],
                        max_length=20,
                    ),
                ),
                ("notice_version", models.CharField(max_length=50)),
                ("consented_at", models.DateTimeField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("self_service", "Self-service"),
                            ("paper_form", "Paper form"),
                            ("staff_recorded", "Staff-recorded"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenancy.church"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to="people.person",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_records_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="people.consentrecord",
                    ),
                ),
            ],
            options={
                "db_table": "person_consent_record",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["church", "person", "created_at"],
                        name="person_cons_church__15eff1_idx",
                    ),
                    models.Index(
                        fields=["church", "status", "created_at"],
                        name="person_cons_church__087522_idx",
                    ),
                ],
            },
        ),
    ]
