# Generated by Django 5.2.16 on 2026-07-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_person_anonymized_at_person_deactivated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="wechat_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
