# Generated by Django 5.2.17 on 2026-08-12 16:26

import re
from collections import defaultdict

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_normalized_contacts(apps, schema_editor):
    Person = apps.get_model("people", "Person")
    ConsentRecord = apps.get_model("people", "ConsentRecord")
    rows = list(Person.objects.values("id", "church_id", "email", "phone"))
    email_matches = defaultdict(list)
    for row in rows:
        email = (row["email"] or "").strip().casefold() or None
        if email:
            email_matches[(row["church_id"], email)].append(row["id"])
    collisions = [
        (church_id, sorted(ids))
        for (church_id, _email), ids in email_matches.items()
        if len(ids) > 1
    ]
    if collisions:
        details = "; ".join(
            f"church_id={church_id} person_ids={ids}"
            for church_id, ids in sorted(collisions)
        )
        raise RuntimeError(
            "Normalized email collisions require human review before migration: "
            + details
        )

    for row in rows:
        email = (row["email"] or "").strip().casefold() or None
        phone = re.sub(r"\D", "", row["phone"] or "") or None
        if phone and phone.startswith("00"):
            phone = phone[2:] or None
        Person.objects.filter(pk=row["id"]).update(
            normalized_email=email,
            normalized_phone=phone,
        )
    # Historical authenticated submissions labelled self-service had a staff
    # recorder. Preserve the actor and describe those honestly as staff-recorded.
    ConsentRecord.objects.filter(
        method="self_service", recorded_by__isnull=False
    ).update(method="staff_recorded")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_person_wechat_id"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="normalized_email",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="normalized_phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consent_records_recorded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(populate_normalized_contacts, noop_reverse),
        migrations.AddConstraint(
            model_name="consentrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("method", "self_service"), ("recorded_by__isnull", True)),
                    models.Q(
                        models.Q(("method", "self_service"), _negated=True),
                        ("recorded_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="consent_recorder_matches_method",
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                condition=models.Q(("normalized_email__isnull", False)),
                fields=("church", "normalized_email"),
                name="uniq_person_normalized_email_per_church",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["church", "normalized_phone"],
                name="person_church__1c59d7_idx",
            ),
        ),
    ]
