# Generated by Django 5.2.16 on 2026-07-16 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("care", "0001_initial"),
        ("people", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="carecase",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="care_cases",
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="follow_ups_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="church",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenancy.church"
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_ups",
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="interaction",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="interactions_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interaction",
            name="care_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interactions",
                to="care.carecase",
            ),
        ),
        migrations.AddField(
            model_name="interaction",
            name="church",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenancy.church"
            ),
        ),
        migrations.AddField(
            model_name="interaction",
            name="follow_up",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interactions",
                to="care.followup",
            ),
        ),
        migrations.AddField(
            model_name="interaction",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="people.person",
            ),
        ),
        migrations.AddIndex(
            model_name="carecase",
            index=models.Index(
                fields=["church", "status", "urgency"],
                name="care_case_church__897f53_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["church", "assigned_to", "status"],
                name="follow_up_church__f10d7c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="followup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "closed"), _negated=True),
                fields=("person",),
                name="follow_up_one_open_per_person",
            ),
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                fields=["church", "person", "occurred_at"],
                name="interaction_church__7e951d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="interaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("follow_up__isnull", True),
                    ("care_case__isnull", True),
                    _connector="OR",
                ),
                name="interaction_one_context",
            ),
        ),
    ]
