# Generated by Django 5.2.16 on 2026-08-12 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_schedule_anchors(apps, schema_editor):
    FollowUp = apps.get_model("care", "FollowUp")
    FollowUp.objects.update(
        status_changed_at=models.F("updated_at"),
        due_schedule_changed_at=models.F("updated_at"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0002_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="followup",
            name="due_schedule_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_schedule_anchors,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="followup",
            name="status_changed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="followup",
            name="due_schedule_changed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="FollowUpDueDateChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_due_at", models.DateField(blank=True, null=True)),
                ("new_due_at", models.DateField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("awaiting_response", "Awaiting response"),
                            ("person_requested", "Person requested"),
                            ("worker_availability", "Worker availability"),
                            ("other_operational", "Other operational"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_up_due_date_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenancy.church"
                    ),
                ),
                (
                    "follow_up",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="due_date_changes",
                        to="care.followup",
                    ),
                ),
                (
                    "interaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="due_date_changes",
                        to="care.interaction",
                    ),
                ),
            ],
            options={
                "db_table": "follow_up_due_date_change",
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["follow_up", "created_at"],
                        name="follow_up_d_follow__672873_idx",
                    )
                ],
            },
        ),
    ]
