# Generated by Django 5.2.16 on 2026-07-17 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("auth.login_succeeded", "Login succeeded"),
                            ("auth.login_failed", "Login failed"),
                            ("care.confidential_viewed", "Confidential care viewed"),
                            ("person.created", "Person created"),
                            ("person.updated", "Person updated"),
                            ("person.deactivated", "Person deactivated"),
                            ("membership.role_changed", "Membership role changed"),
                            ("membership.access_changed", "Membership access changed"),
                            ("data.csv_exported", "CSV exported"),
                        ],
                        max_length=40,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=100)),
                ("target_id", models.CharField(blank=True, max_length=100)),
                ("request_id", models.UUIDField(db_index=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="tenancy.church",
                    ),
                ),
            ],
            options={
                "db_table": "audit_event",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["church", "action", "created_at"],
                        name="audit_event_church__32b622_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="audit_event_actor_i_032040_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_event_target__92b051_idx",
                    ),
                ],
            },
        ),
    ]
