# Generated by Django 5.2.16 on 2026-07-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditevent_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("auth.login_succeeded", "Login succeeded"),
                    ("auth.login_failed", "Login failed"),
                    ("care.confidential_viewed", "Confidential care viewed"),
                    ("person.created", "Person created"),
                    ("person.updated", "Person updated"),
                    ("person.deactivated", "Person deactivated"),
                    ("person.anonymized", "Person anonymized"),
                    ("person.hard_deleted", "Person hard deleted"),
                    ("membership.role_changed", "Membership role changed"),
                    ("membership.access_changed", "Membership access changed"),
                    ("data.csv_exported", "CSV exported"),
                    ("consent.recorded", "Consent recorded"),
                ],
                max_length=40,
            ),
        ),
    ]
