# Generated by Django 5.2.17 on 2026-09-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_alter_auditevent_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("auth.login_succeeded", "Login succeeded"),
                    ("auth.login_failed", "Login failed"),
                    ("care.confidential_viewed", "Confidential care viewed"),
                    ("person.created", "Person created"),
                    ("person.updated", "Person updated"),
                    ("person.deactivated", "Person deactivated"),
                    ("person.anonymized", "Person anonymized"),
                    ("person.hard_deleted", "Person hard deleted"),
                    ("membership.role_changed", "Membership role changed"),
                    ("membership.access_changed", "Membership access changed"),
                    ("data.csv_exported", "CSV exported"),
                    ("consent.recorded", "Consent recorded"),
                    ("event.public_link_created", "Public event link created"),
                    ("event.public_link_recovered", "Public event link recovered"),
                    ("event.public_link_revoked", "Public event link revoked"),
                    ("event.public_registered", "Public event registration created"),
                    ("event.public_cancelled", "Public event registration cancelled"),
                ],
                max_length=40,
            ),
        ),
    ]
